#!/bin/bash

# Symlink configs to home folder
ln -s `realpath ./.zshrc` `realpath ..`/.zshrc
ln -s `realpath ./.vimrc` `realpath ..`/.vimrc
ln -s `realpath ./.vimrc.plug` `realpath ..`/.vimrc.plug
ln -s `realpath ./.tmux.conf` `realpath ..`/.tmux.conf
